### ISSUE TITLE
2.0: API - Clusters should default to being multi AZ

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#951]
When creating a cluster and adding a region, the user shouldn't be able to select an AZ as the cluster should default to spinning up in multi-zones.

**Comment by stgleb** [comment]
DigitalOcean doesn't have availability zones,
for GCE there are no problems doing that - it requires changes only in UI
in AWS this is more complicated because SG creates security groups for instances
and security group belongs to availability zone. We must be able to access each node from another one
so N security groups will requires N^2/2 relations between them.
