### ISSUE TITLE
2.0.1: UI - 404's in browser logs as cluster is provisioning.

### ISSUE THREAD

**Issue by eldridgeh** [supergiant/control#955]
**Short Summary:**
When spinning up a cluster and opening the devtools in the browser , a bunch of 404's are found. There is nothing broken but the UI is waiting for the cluster to be ready.
We need to make these 404's pretty so users do not think there is an issue.
We could possibly say 'Waiting for cluster to be ready' etc.

**Comment by stgleb** [comment]
Well, error happens on request to list cluster tasks. This happens because task asynchronous nature.
It creates itself in database when it starts run, which happens slightly after cluster provisioning starts.
That's why you can have 404 in browser developer tools for each task a few times. 

When you fire provisioning request control reply with 202 that is used for async action
and it doesn't mean that all entities has been created at that time. So this is by design.
